import quantum_music
from quantum_music import make_music_video, get_instruments, make_music_midi
import qiskit
from qiskit import QuantumCircuit

repeats = 2

c = QuantumCircuit(5)

for i in range(repeats):
    if i==0:
        c.x(2)
        c.x(3)
    c.barrier()
    c.barrier()
    c.x(0)
    c.x(3)
    c.h(3)
    c.cx(3,0)
    c.cx(3,1)
    c.barrier()
    c.cx(3,1)
    c.barrier()
    c.cx(3,4)
    c.cx(4,3)
    c.cx(4,2)
    c.cx(4,0)
    c.barrier()
    c.x(0)
    c.x(2)
    c.cx(4,2)
    c.barrier()
    c.cx(4,3)
    c.cx(4,2)
    c.cx(3,4)
    c.barrier()
    c.barrier()
    c.cx(2,1)
    c.barrier()
    c.cx(2,1)
    c.barrier()
    c.cx(3,4)
    c.cx(2,1)
    c.cx(2,0)
    c.cx(4,3)
    c.cx(1,2)
    c.barrier()
    c.x(0)
    c.x(2)
    c.cx(4,2)
    c.cx(1,0)
    c.cx(4,1)
    c.barrier()
    c.cx(4,0)
    c.cx(4,2)
    c.cx(4,3)
    c.cx(3,4)
    c.barrier()
    c.barrier()
    c.cx(3,4)
    c.cx(3,2)
    c.barrier()
    c.cx(4,0)
    c.cx(4,2)
    c.cx(4,3)
    c.barrier()
    c.x(2)
    c.x(3)
    c.cx(4,3)
    c.barrier()
    c.x(0)
    c.x(1)
    c.cx(4,1)
    c.barrier()
    c.cx(4,3)
    c.cx(4,2)
    c.cx(4,1)
    c.cx(2,4)
    c.barrier()
    c.x(0)
    c.cx(2,4)
    c.cx(2,3)
    c.cx(2,0)
    c.barrier()
    c.barrier()
    c.x(0)
    c.x(1)
    c.x(2)
    c.cx(0,2)
    c.barrier()
    c.cx(0,2)
    c.barrier()
    c.x(2)
    c.x(3)
    c.cx(4,3)
    c.cx(2,1)
    c.cx(1,2)
    c.barrier()
    c.x(0)
    c.x(2)
    c.cx(4,2)
    c.cx(4,1)
    c.cx(4,0)
    c.barrier()
    if i+1 != repeats:
        c.cx(4,2)
        c.h(4)
        c.x(3)
        c.x(0)


time_list = [[80,0],[40,0],[120,0],[120,0],[120,0],[240,0],
             [80,0],[40,0],[120,0],[120,0],[120,0],[240,0],
             [80,0],[40,0],[120,0],[120,0],[120,0],[120,0],[120,0],
             [80,0],[40,0],[120,0],[120,0],[120,0],[240,0],]*repeats

# slow down by factor s
s = 2
time_list = [[s*t for t in tt] for tt in time_list]

#make_music_video(c, "happy_bday_bassline", time_list, 0.01, 0.02, [get_instruments("pipe"), get_instruments("reed"), get_instruments("brass"), get_instruments("organ")])
make_music_midi(c, "happy_bday_bassline", time_list, 0.02, 0.04, [[75], get_instruments("pipe"), get_instruments("pipe"), get_instruments("reed"), get_instruments("brass"), get_instruments("organ")])